// src/app/data.ts

export const TRANSLATIONS = {
  id: {
    Lion: "Singa",
    Tiger: "Harimau",
    Elephant: "Gajah",
    Giraffe: "Jerapah",
    Zebra: "Zebra",
    Panda: "Panda",
    Bunny: "Kelinci",
    Pigeon: "Burung Merpati",
    Goose: "Angsa",
    Duck: "Bebek",
    Cat: "Kucing",
    Dog: "Anjing",
    Squirrel: "Tupai",
    Horse: "Kuda",
    Cow: "Sapi",
    Sheep: "Domba",
    Turtle: "Kura-kura",
    Fish: "Ikan",
    Sparrow: "Burung Gereja",
    Owl: "Burung Hantu",
    Butterfly: "Kupu-kupu",
    Bee: "Lebah",
    Fox: "Rubah",
    Deer: "Rusa",
    Wolf: "Serigala",
    Hippo: "Kuda Nil",
    Rhino: "Badak",
    Bekantan: "Bekantan",
    Orangutan: "Orangutan",
    Tapir: "Tapir",
    Komodo: "Komodo",
    Anoa: "Anoa",
  },
  en: {
    Lion: "Lion",
    Tiger: "Tiger",
    Elephant: "Elephant",
    Giraffe: "Giraffe",
    Zebra: "Zebra",
    Panda: "Panda",
    Bunny: "Bunny",
    Pigeon: "Pigeon",
    Goose: "Goose",
    Duck: "Duck",
    Cat: "Cat",
    Dog: "Dog",
    Squirrel: "Squirrel",
    Horse: "Horse",
    Cow: "Cow",
    Sheep: "Sheep",
    Turtle: "Turtle",
    Fish: "Fish",
    Sparrow: "Sparrow",
    Owl: "Owl",
    Butterfly: "Butterfly",
    Bee: "Bee",
    Fox: "Fox",
    Deer: "Deer",
    Wolf: "Wolf",
    Hippo: "Hippo",
    Rhino: "Rhino",
    Bekantan: "Proboscis Monkey",
    Orangutan: "Orangutan",
    Tapir: "Tapir",
    Komodo: "Komodo Dragon",
    Anoa: "Anoa",
  },
};

export const BASE_PATH =
  process.env.NODE_ENV === "production" ? "/animal-1" : "";

export const ANIMALS = [
  { id: "lion", key: "Lion", image: `${BASE_PATH}/animals/lion.png` },
  { id: "tiger", key: "Tiger", image: `${BASE_PATH}/animals/tiger.png` },
  {
    id: "elephant",
    key: "Elephant",
    image: `${BASE_PATH}/animals/elephant.png`,
  },
  { id: "giraffe", key: "Giraffe", image: `${BASE_PATH}/animals/giraffe.png` },
  { id: "zebra", key: "Zebra", image: `${BASE_PATH}/animals/zebra.png` },
  { id: "panda", key: "Panda", image: `${BASE_PATH}/animals/panda.png` },
  { id: "bunny", key: "Bunny", image: `${BASE_PATH}/animals/bunny.png` },
  { id: "pigeon", key: "Pigeon", image: `${BASE_PATH}/animals/pigeon.png` },
  { id: "goose", key: "Goose", image: `${BASE_PATH}/animals/goose.png` },
  { id: "duck", key: "Duck", image: `${BASE_PATH}/animals/duck.png` },
  { id: "cat", key: "Cat", image: `${BASE_PATH}/animals/cat.png` },
  { id: "dog", key: "Dog", image: `${BASE_PATH}/animals/dog.png` },
  {
    id: "squirrel",
    key: "Squirrel",
    image: `${BASE_PATH}/animals/squirrel.png`,
  },
  { id: "horse", key: "Horse", image: `${BASE_PATH}/animals/horse.png` },
  { id: "cow", key: "Cow", image: `${BASE_PATH}/animals/cow.png` },
  { id: "sheep", key: "Sheep", image: `${BASE_PATH}/animals/sheep.png` },
  { id: "turtle", key: "Turtle", image: `${BASE_PATH}/animals/turtle.png` },
  { id: "fish", key: "Fish", image: `${BASE_PATH}/animals/fish.png` },
  { id: "sparrow", key: "Sparrow", image: `${BASE_PATH}/animals/sparrow.png` },
  { id: "owl", key: "Owl", image: `${BASE_PATH}/animals/owl.png` },
  {
    id: "butterfly",
    key: "Butterfly",
    image: `${BASE_PATH}/animals/butterfly.png`,
  },
  { id: "bee", key: "Bee", image: `${BASE_PATH}/animals/bee.png` },
  { id: "fox", key: "Fox", image: `${BASE_PATH}/animals/fox.png` },
  { id: "deer", key: "Deer", image: `${BASE_PATH}/animals/deer.png` },
  { id: "wolf", key: "Wolf", image: `${BASE_PATH}/animals/wolf.png` },
  { id: "hippo", key: "Hippo", image: `${BASE_PATH}/animals/hippo.png` },
  { id: "rhino", key: "Rhino", image: `${BASE_PATH}/animals/rhino.png` },
  {
    id: "bekantan",
    key: "Bekantan",
    image: `${BASE_PATH}/animals/bekantan.png`,
  },
  {
    id: "orangutan",
    key: "Orangutan",
    image: `${BASE_PATH}/animals/orangutan.png`,
  },
  { id: "tapir", key: "Tapir", image: `${BASE_PATH}/animals/tapir.png` },
  { id: "komodo", key: "Komodo", image: `${BASE_PATH}/animals/komodo.png` },
  { id: "anoa", key: "Anoa", image: `${BASE_PATH}/animals/anoa.png` },
];
